builds:
  - binary: miflo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/gavsidhu/miflo/cmd.Version={{.Version}}

checksum:
  name_template: 'checksums.txt'
