builds:
  - binary: miflo
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/gavsidhu/miflo/cmd.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm

release:
  prerelease: auto

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'
