version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  sqld:
    image: ghcr.io/libsql/sqld:latest
    ports:
      - "8080:8080"
volumes:
  pgdata:

